[metadata]
creation_date = "2025/02/04"
maturity = "production"
updated_date = "2025/02/04"

[rule]
author = ["Elastic"]
description = """
This rule is triggered when an email indicator from the Threat Intel Filebeat module or integrations matches an event
containing email-related data, such as logs from email security gateways or email service providers.
"""
from = "now-65m"
index = ["filebeat-*", "logs-*"]
interval = "1h"
language = "kuery"
license = "Elastic License v2"
name = "Threat Intel Email Indicator Match"
references = [
    "https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-threatintel.html",
    "https://www.elastic.co/guide/en/security/current/es-threat-intel-integrations.html",
    "https://www.elastic.co/security/tip",
]
risk_score = 99
rule_id = "fcf18de8-ad7d-4d01-b3f7-a11d5b3883af"
setup = """## Setup

This rule needs threat intelligence indicators to work.
Threat intelligence indicators can be collected using an [Elastic Agent integration](https://www.elastic.co/guide/en/security/current/es-threat-intel-integrations.html#agent-ti-integration),
the [Threat Intel module](https://www.elastic.co/guide/en/security/current/es-threat-intel-integrations.html#ti-mod-integration),
or a [custom integration](https://www.elastic.co/guide/en/security/current/es-threat-intel-integrations.html#custom-ti-integration).

More information can be found [here](https://www.elastic.co/guide/en/security/current/es-threat-intel-integrations.html).
"""
severity = "critical"
tags = ["Rule Type: Threat Match"]
threat_index = ["filebeat-*", "logs-ti_*"]
threat_indicator_path = "threat.indicator"
threat_language = "kuery"
threat_query = """
@timestamp >= "now-30d/d" and event.module:(threatintel or ti_*) and threat.indicator.email.address:* and not
labels.is_ioc_transform_source:"true"
"""
timeline_id = "495ad7a7-316e-4544-8a0f-9c098daee76e"
timeline_title = "Generic Threat Match Timeline"
timestamp_override = "event.ingested"
type = "threat_match"

query = '''
email.from.address:* or email.sender.address:* or email.reply_to.address:* or email.to.address:*
'''


[[rule.threat_filters]]

[rule.threat_filters."$state"]
store = "appState"
[rule.threat_filters.meta]
disabled = false
key = "event.category"
negate = false
type = "phrase"
[rule.threat_filters.meta.params]
query = "threat"
[rule.threat_filters.query.match_phrase]
"event.category" = "threat"
[[rule.threat_filters]]

[rule.threat_filters."$state"]
store = "appState"
[rule.threat_filters.meta]
disabled = false
key = "event.kind"
negate = false
type = "phrase"
[rule.threat_filters.meta.params]
query = "enrichment"
[rule.threat_filters.query.match_phrase]
"event.kind" = "enrichment"
[[rule.threat_filters]]

[rule.threat_filters."$state"]
store = "appState"
[rule.threat_filters.meta]
disabled = false
key = "event.type"
negate = false
type = "phrase"
[rule.threat_filters.meta.params]
query = "indicator"
[rule.threat_filters.query.match_phrase]
"event.type" = "indicator"
[[rule.threat_mapping]]

[[rule.threat_mapping.entries]]
type = "mapping"
field = "email.from.address"
value = "threat.indicator.email.address"

[[rule.threat_mapping]]

[[rule.threat_mapping.entries]]
type = "mapping"
field = "email.to.address"
value = "threat.indicator.email.address"


[[rule.threat_mapping]]

[[rule.threat_mapping.entries]]
type = "mapping"
field = "email.sender.address"
value = "threat.indicator.email.address"

[[rule.threat_mapping]]

[[rule.threat_mapping.entries]]
type = "mapping"
field = "email.reply_to.address"
value = "threat.indicator.email.address"
